# Generated by Django 3.1.4 on 2020-12-29 17:56

from django.db import migrations, models
import django.utils.timezone
import post.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isBoast', models.BooleanField(default=True)),
                ('post', models.CharField(max_length=150)),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('secret_key', models.CharField(default=post.utils.secret_token, max_length=6)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
